baseURL = "https://santi-test.netlify.app/notes"
languageCode = "en-us"
title = "Santi's Index Card System"
theme = "cortex"
contentDir = "content/notes"
publishDir = "public/notes"
staticDir = "static/notes"

[params]
email = "santiyounger@gmail.com"
footer = "Built with ♥ with Org-mode and Hugo."

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
