baseURL = "https://santi-test.netlify.app/"
languageCode = "en-us"
title = "Santi Younger"
theme = "color-your-world"

copyright = "Copyright © 2020 Santi Younger"

enableEmoji = true
enableInlineShortcodes = true

paginate = 5


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    # To make use of the custom Chroma, this should be false
    # The default is true
    noClasses = false


[params]
  
  # Site description
  description = "John Doe's personal website"
  
  # Author
  author      = "John Doe"
  authorDesc  = "Some indescribable horror."
  
  # Site cover, for Open Graph, Twitter Cards and Schema.org
  # It will be used if the current page doesn't have a image cover
  # File will be picked from the "assets" directory
  # Comment the lines if you don't want to use it
  #cover     = "img/cover.jpg"
  #coverAlt  = "A placeholder that doesn't deserve to be described."
  
  # Shows a message in the footer about JavaScript being disabled
  # The default is false
  hasNoscriptNotice = true
  
  # Default path for images in posts
  # ie.: "content/some-post/img"
  # Can also be set PER PAGE
  # It can be used to reduce repetition
  # There's no default value
  imgPath = "img"
  
  # Default classes for markup image 
  # Modifies the default behavior of images placed via markdown
  # Can also be set PER PAGE via front matter
  # Available classes are: border and borderless
  # There's no default value
  markupImgClass = ""
  
  # This will append a separator (of your choice) along the site title to your <title>
  # You can disabled it PER PAGE by using "disableTitleSeparator" at front
  # matter or disable it entirely by commenting the line below
  # ie.: | ❚ - – — • ⚫ 
  titleSeparator = "|"
  
  
  # Contact form shortcode
  [params.contact]
  
    # formspree.io Form ID
    formspreeFormId = "santiyounger@gmail.com"
    
    # Autocomplete [on/off] and min character length for message
    autoComplete      = false # Default is false
    messageMinLength  = 1   # Default is 140
    
    # Subject
    # You can set a single value below (and it will cease to be a dropdown),
    # BUT KEEP IT AS AN ARRAY
    # It can also be disabled entirely (and it will turn into a text field)
    subject = [ "Consulting", "Just Saying Hi", "Business Question", "Other" ]

    # Text placeholders. As usual, comment the lines if you don't want use them
    # The "subject" below will only be used if the "subject" above doesn't exist (ie.: commented/deleted)
    [params.contact.placeholder]
      name    = "John Doe"
      email   = "johndoe@example.com"
      subject = 'Just saying "hi"'
      message = "Type your message here."


  [params.search]
  
    # Enable search form (at the post list)
    # The default value is false
    enable = true
  
    # Limit search results
    # The default value is 30
    maxResults = 15
    
    # Limit seach field input and pattern matching
    minLength = 2   # Default is 3
    maxLength = 42  # Default is 32
    
    # Optional placeholder for search field
    placeholder = "ie.: lorem ipsum"
    

  [params.style]
  
    # Dark mode as default
    # The default is false
    isDark = true
  
    # Accent colors for light and dark mode respectively
    lightAccent  = "#1f676b" # Default is "#225670"
    darkAccent   = "#EB8D00" # Default is "#dd587c"

    # More colors, pick as many as you want (not really sure if there's a limit)
    # Apparently these may not show up on every modern browser (ie. Firefox)
    # There's no default value. Used here just as example
    presets = [ "#1f676b", "#f3a530", "#902b37", "#1dbc91", "#754e85", "#7fc121", "#a8314a", "#ff7433", "#3e6728", "#c063bd" ]
    
    # Use an icon or text for footnote return links
    # The default is false
    hasIconAsFootnoteReturnLink = true
    
    # For the social shortcode
    # Use flexbox (with flex-grow) or grid (equal width)
    # The default is false
    socialIsFlex = true
    
    # Keep anchor links hidden until it's focused/hovered
    # They will always be visible in mobile devices, regardless the option
    # The default is false
    hideAnchors = true
    
    # To make use of the custom Chroma, this should be true
    # and "noClasses" (at markup.highlight) should be false
    # The default is true
    useCustomChroma = true

    # CSS animation transition when changing colors
    # The default is ".5s ease"
    changeTransition = ".3s ease"
    
    
  # For a simple 404
  [params.notFound]
    title         = "Page not found"
    description   = "This page was not found."
    paragraph     = "Nothing to see here, buddy."
    
  [params.social.centralized]
    # facebook      = [ "<username>", "Zuckerburg" ]
    # flickr        = [ "<username>" ]
    github        = [ "santiyounger" ]
    # gitlab        = [ "santiyounger" ]
    instagram     = [ "santiyounger" ]
    # keybase       = [ "<username>" ]
    # linkedin      = [ "<username>" ]
    # medium        = [ "<username>" ]
    # reddit        = [ "<username>" ]
    # soundcloud    = [ "<username>" ]
    # stackOverflow = [ "<username>" ]
    # strava        = [ "<username>" ]
    # telegram      = [ "<username>" ]
    # twitch        = [ "<username>" ]
    twitter       = [ "santiyounger", "@santiyounger" ]
    # vimeo         = [ "<username>" ]
    # whatsapp      = [ "<number>" ]
    youtube       = [ "UChuGtKiYN0M-R5Bd2yiwOGA" ]
    #entry         = [ "username", "label (optional)" ]
    
    # The "entry" here IS important. It's used to load the data.

  [params.social.decentralized]
  
# start of commenting out
    # [params.social.decentralized.element]
    #   1 = [ "https://app.element.io/#/user/<username>:matrix.org", "matrix.org" ]
    #   #entry = [ "full url", "label (required)" ]
      
    # [params.social.decentralized.funkwhale]
    #   1 = [ "https://open.audio/<username>", "open.audio" ]
      
    # [params.social.decentralized.mastodon]
    #   1 = [ "https://mastodon.social/<username>", "mastodon.social" ]
    #   2 = [ "https://mastodon.too/<username>", "mastodon.too" ]
    #   3 = [ "https://yet.another.one/<username>", "yet.another.one" ]
      
    # [params.social.decentralized.matrix]
    #   1 = [ "https://matrix.to/#/<username>:matrix.org", "matrix.org" ]
    #   2 = [ "https://matrix.to/#/<username>:other.org", "other.org" ]
      
    # [params.social.decentralized.peertube]
    #   1 = [ "https://peertube.something/accounts/<username>", "peertube.something" ]
      
    # [params.social.decentralized.pixelfed]
    #   1 = [ "https://pixelfed.social/<username>", "pixelfed.social" ]

# end of commenting out
      
    # The "entry" here ISN'T important. It's used for nothing.
    
    
[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true



[languages]

  [languages.en]
  
    languageName = "English"

    [languages.en.menu]

      [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "about/"

      [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "posts/"

      [[languages.en.menu.main]]
        name = "Podcast"
        weight = 3
        url = "podcast/"

      [[languages.en.menu.main]]
        name = "Notes"
        weight = 4
        url = "notes/"

      [[languages.en.menu.main]]
        name = "Contact"
        weight = 5
        url = "contact/"

